### ISSUE TITLE
FAISS do not works in OSX (fails to find `/opt/homebrew/opt/libomp/lib/libomp.dylib`)

### ISSUE THREAD

**Issue by carlopi** [duckdb-faiss-ext/duckdb-faiss-ext#17]
I was trying a few things around community extensions, and found unexpected that on MacOS `faiss` requires extra dynamic libraries. 
I was unsure whether this is expected or not, and though of letting you know.
This DO NOT actually require fixing, might be fine like it is.

---

Repro:
```sql
INSTALL faiss from community;
LOAD faiss;
```
Error:
```
IO Error: Extension "/Users/carlo/.duckdb/extensions/v1.1.1/osx_arm64/faiss.duckdb_extension" could not be loaded: dlopen(/Users/carlo/.duckdb/extensions/v1.1.1/osx_arm64/faiss.duckdb_extension, 0x0006): Library not loaded: /opt/homebrew/opt/libomp/lib/libomp.dylib
  Referenced from: <8C80FAA1-724D-3F8E-9546-0E7F45F44BC7> /Users/carlo/.duckdb/extensions/v1.1.1/osx_arm64/faiss.duckdb_extension
  Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file)
```
Details of the system:
```sql
D PRAGMA version;
┌─────────────────┬────────────┐
│ library_version │ source_id  │
│     varchar     │  varchar   │
├─────────────────┼────────────┤
│ v1.1.1          │ af39bd0dcf │
└─────────────────┴────────────┘
D PRAGMA platform;
┌───────────┐
│ platform  │
│  varchar  │
├───────────┤
│ osx_arm64 │
└───────────┘
D PRAGMA user_agent;
┌──────────────────────────────┐
│          user_agent          │
│           varchar            │
├──────────────────────────────┤
│ duckdb/v1.1.1(osx_arm64) cli │
└──────────────────────────────┘
D SELECT extension_name, extension_version, installed_from  FROM duckdb_extensions() WHERE extension_name = 'faiss';
┌────────────────┬───────────────────┬────────────────┐
│ extension_name │ extension_version │ installed_from │
│    varchar     │      varchar      │    varchar     │
├────────────────┼───────────────────┼────────────────┤
│ faiss          │ ac09d01           │ community      │
└────────────────┴───────────────────┴────────────────┘
```

**Comment by arjenpdevries** [comment]
I don't know if we can avoid such errors - FAISS needs OpenMP so you will most likely need it on your system for being able to use this extension meaningfully.

The extension is still in an early stage BTW. We are grateful for all feedback, including these reports!

What happens if you install OpenMP first? I'm not an Apple user, but probably you can install it using brew?

```
brew install libomp
```

**Comment by JAicewizard** [comment]
Faiss indeed is dependant on omp. Libomp is very much a requirement for FAISS. C++ executables are always dependant on runtime libraries, just like it is dependant on libc, libstdc++, libpthread etc. For the FAISS extension all of the runtime dependencies are required by the compiler, there is no way to get rid of these. Just as DuckDB doesn't work without `/usr/lib/libc.so.6` on linux, FAISS doesn't without `/opt/homebrew/opt/libomp/lib/libomp.dylib` on linux (on linux you can see this with `ldd {BINARY}`).

I don't know if we can handle this better on the extension side, maybe we could instruct duckdb to give an appropriate error message? But that would have to be done using some config file or other meta-data. Are you willing to get something like this to work? Otherwise I will close this, since there is nothing we can do about this.

I was personally just surprised apple doesn't ship omp, this is also the reason that the openmp toolchain needed in the extension CI tools.

**Comment by carlopi** [comment]
After `brew install libomp` works, yes, that was I also assumed but had not explicitly tried.

I guess then if this is expected maybe it can be worth adding to the README?
It was just surprising/unexpected to me.

**Comment by carlopi** [comment]
Sure, this can be closed. It's working as expected.

Error message can be potentially improved, but yes, this does requires some coordination with DuckDB, so likely not worth at this moment / to be looked up at some other time.

**Comment by JAicewizard** [comment]
> I guess then if this is expected maybe it can be worth adding to the README?

yes it was already in the works, I guess if you say it works I will merge it now.
