### ISSUE TITLE
Cannot add data to index

### ISSUE THREAD

**Issue by caseylai** [duckdb-faiss-ext/duckdb-faiss-ext#19]
Tried to add data to index with/without id, but both failed.

![image](https://github.com/user-attachments/assets/b953145b-a862-4cb1-862f-129349a92245)

D CALL FAISS_ADD((SELECT _id, abstract_embedding FROM keyan), 'keyan_abstract_embedding_faiss_hnsw_idx');
Run Time (s): real 0.192 user 1.171861 sys 8.343244
Invalid Input Error: Unable to add data: Error in virtual void faiss::Index::add_with_ids(faiss::idx_t, const float*, const idx_t*) at /duckdb_build_dir/faiss/faiss/Index.cpp:45: add_with_ids not implemented for this type of index

D CALL FAISS_ADD((SELECT abstract_embedding FROM keyan), 'keyan_abstract_embedding_faiss_hnsw_idx');
Run Time (s): real 0.047 user 0.002671 sys 0.000000
Invalid Input Error: Tried to insert data without labels, when index was previously added with labels. Cannot mix index data with and without labels

**Comment by JAicewizard** [comment]
Ah I see what is wrong here. The last error should be self-explanatory, but the situation is a bit odd. This should be an easy fix.
For now, I think the real solution for you would be to add an `IDMap` to the faiss index. So the index string would be `IDMap, HNSW32` instead of `HNSW32` if I recall correctly.

This is because the HNSW index doesn't support adding with IDs, and needs an IDMap around it, this is a limitation of faiss.

Does this solution help?

**Comment by caseylai** [comment]
Yes, it works! Thank you @JAicewizard
